/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface CurrencyItem {
        "rate": number;
        "symbol": string;
        "value": number;
    }
    interface ExchangeDisplay {
        "baseValue": number;
        "selectedSymbols": Array<string>;
        "symbols": Array<string>;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLCurrencyItemElement extends Components.CurrencyItem, HTMLStencilElement {
    }
    var HTMLCurrencyItemElement: {
        prototype: HTMLCurrencyItemElement;
        new (): HTMLCurrencyItemElement;
    };
    interface HTMLExchangeDisplayElement extends Components.ExchangeDisplay, HTMLStencilElement {
    }
    var HTMLExchangeDisplayElement: {
        prototype: HTMLExchangeDisplayElement;
        new (): HTMLExchangeDisplayElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "currency-item": HTMLCurrencyItemElement;
        "exchange-display": HTMLExchangeDisplayElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface CurrencyItem {
        "onBaseChange"?: (event: CustomEvent<any>) => void;
        "onRemoveSymbol"?: (event: CustomEvent<any>) => void;
        "rate"?: number;
        "symbol"?: string;
        "value"?: number;
    }
    interface ExchangeDisplay {
        "baseValue"?: number;
        "selectedSymbols"?: Array<string>;
        "symbols"?: Array<string>;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "currency-item": CurrencyItem;
        "exchange-display": ExchangeDisplay;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "currency-item": LocalJSX.CurrencyItem & JSXBase.HTMLAttributes<HTMLCurrencyItemElement>;
            "exchange-display": LocalJSX.ExchangeDisplay & JSXBase.HTMLAttributes<HTMLExchangeDisplayElement>;
        }
    }
}
